apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: {{appName}}
    env: {{env}}
  name: {{appName}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{appName}}
    spec:
      containers:
      - image: rabbitmq
        name: {{appName}}
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m