apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{appName}}
spec:
  replicas: 1
  template:
      metadata:
        labels:
            app: {{appName}}
            env: {{env}}
      spec:
        containers:
        - name: {{appName}}
          image: {{stubrunnerImg}}
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: SPRING_RABBITMQ_ADDRESSES
            value: "{{rabbitAppName}}-service"
          - name: eureka_client_serviceUrl_defaultZone
            value: "http://{{eurekaAppName}}:8761/eureka/"
          - name: STUBRUNNER_IDS
            value: "{{stubrunnerIds}}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3